#!/bin/bash 

function restore_saved_artifacts() {
  if [ -f /tmp/artifacts/maven.tar.gz ]; then
    pushd / &> /dev/null
    echo -n "Restoring saved artifacts from prior build..."
    tar zxf /tmp/artifacts/maven.tar.gz
    echo "...done"
    popd &> /dev/null
  fi
}

local_source_dir=/opt/jboss-eap-6.2/sti-source
artifact_dir=/opt/jboss-eap-6.2/artifacts

mkdir -p $local_source_dir
mkdir -p $artifact_dir

cp -ad /tmp/src/* $local_source_dir

if [ -f "$local_source_dir/pom.xml" ]; then
  restore_saved_artifacts
  pushd $local_source_dir &> /dev/null
  mvn package

  if [ $? -ne 0 ]; then
    exit $?
  fi

  echo -n "Copying built war files into $artifact_dir for later deployment..."
  cp target/*.war $artifact_dir/
  echo "...done"

  popd &> /dev/null
else
  echo -n "Copying binaries in source directory into $artifact_dir for later deployment..."
  cp $local_source_dir/*.war $artifact_dir/
  echo "...done"
fi

